[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"

[dev]
  command = "npm run dev"
  port = 5173
  
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
